> **Jupyter slideshow:** This notebook can be displayed as slides. To view it as a slideshow in your browser type in the console:


> `> jupyter nbconvert [this_notebook.ipynb] --to slides --post serve`


> To toggle off the slideshow cell formatting, click the `CellToolbar` button, then `View --> Cell Toolbar --> None`

<img src="http://imgur.com/1ZcRyrc.png" style="float: left; margin: 20px; height: 55px">

# Linear algebra: review of basic concepts with numpy

_Authors: Phillippa Thomson (NYC)_

---

<a id="learning-objectives"></a>
<a id="learning-objectives"></a>
### Learning Objectives
- Recognize scalars, vectors, and matricies.
- Know how to calculate additions and dot products of vectors and matricies.
- Implement basic linear algebra concepts in NumPy.
- Recognize uses of linear algebra in machine learning.

### Lesson Guide
- [Scalars, vectors and matrices](#scalars-vectors-and-matrices)
- [Types of vectors](#types-of-vectors)
	- [Vectors and Matricies are useful for multi-dimensional concepts](#vectors-and-matricies-are-useful-for-multi-dimensional-concepts)
- [Basic matrix algebra](#basic-matrix-algebra)
	- [Addition and substraction](#addition-and-substraction)
	- [Scalar multiplication](#scalar-multiplication)
	- [Vector norm](#vector-norm)
	- [Dot product](#dot-product)
	- [Matrix multiplication](#matrix-multiplication)
	- [The identity matrix](#the-identity-matrix)
- [Applications to machine learning](#applications-to-machine-learning)
	- [Distance between actual values and predicted values](#distance-between-actual-values-and-predicted-values)
	- [Least squares](#least-squares)
- [Independent practice](#independent-practice)
- [Additional resources](#additional-resources)


In [2]:
import numpy as np

<a id="scalars-vectors-and-matrices"></a>
## Scalars, vectors and matrices
---

A **scalar** is a single number.

### $$a$$

A **vector** is several numbers in sequence.

### $$\vec{u} = \left[ \begin{array}{c}
1&3&7
\end{array} \right]$$

In [3]:
# Make the vector using numpy

z = np.array([1,3,5,6])

An '`m x n`' **matrix** is a rectangular array of numbers with '`m`' rows and '`n`' columns. Each number in the matrix is an entry. Entries can be denoted $a_{mn}$

### $$A= \left[ \begin{array}{c}
a_{11} & a_{12} & ... & a_{1n}  \\
a_{21} & a_{22} & ... & a_{2n}  \\
... & ... & ... & ... \\
a_{m1} & a_{m2} & ... & a_{mn}
\end{array} \right]$$

### $$A \in \mathbb{R}^{mn}$$

In [9]:
# make the matrix using numpy

s = np.array([[1,2,3,4],
             [4,5,6,7],
             [8,9,10,11]])
s


array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

<a id="types-of-vectors"></a>
## Types of vectors
---

A (column) **vector** is a matrix with a single column. Entries are components.

### $$\vec{v} = \left[ \begin{array}{c}
1 \\
3 \\
7 \\
\end{array} \right]$$

$\vec{v} \in \mathbb{R}^{n}$, where $\mathbb{R}^{n}$ is n-dimensional real coordinate space. It includes all possible real-valued n-tuples, i.e. $\vec{v}$.


Components are denoted $v_{i}$.

In [4]:
# create v as a 2-dimensional matrix (three rows & one column)



A matrix with a single row is a **row vector**.

### $$\vec{u} = \left[ \begin{array}{c}
1&3&7
\end{array} \right]$$

In [5]:
# create u as a 2-dimensional matrix (one row & three columns)

<a id="vectors-and-matricies-are-useful-for-multi-dimensional-concepts"></a>
<a id="vectors-and-matricies-are-useful-for-multi-dimensional-concepts"></a>
<a id="vectors-and-matricies-are-useful-for-multi-dimensional-concepts"></a>
### Vectors and Matricies are useful for multi-dimensional concepts
![](./assets/images/r3_vectors.png)

We can represent vectors as arrows in n-dimensional space, having magnitude and direction.

(Image from: 
[Louis Scharf, Linear Algebra: Vectors. OpenStax CNX. Sep 17, 2009](http://cnx.org/contents/3d05d982-e21c-4f8a-ab5a-d3e94186f924@6).)

<a id="basic-matrix-algebra"></a>
## Basic matrix algebra

<a id="addition-and-substraction"></a>
### Addition and substaction
Vector **addition** is straightforward. If two vectors are of equal dimensions:

### $$\vec{v} = \left[ \begin{array}{c}
1 \\
3 \\
7
\end{array} \right], \;\; \vec{w} = \left[ \begin{array}{c}
1 \\
0 \\
1
\end{array} \right]$$

In [20]:
# create v and w

v = np.array([1,2,3]).reshape((3,1))
w = np.array([4,5,6]).reshape((3,1))

### $$\vec{v} + \vec{w} =
\left[ \begin{array}{c}
1 \\
3 \\
7
\end{array} \right] + \left[ \begin{array}{c}
1 \\
0 \\
1
\end{array} \right] = 
\left[ \begin{array}{c}
1+1 \\
3+0 \\
7+1
\end{array} \right] = 
\left[ \begin{array}{c}
2 \\
3 \\
8
\end{array} \right]
$$

(Subtraction is similar.)

In [21]:
# compute v + w (column vectors)

v+w

array([[5],
       [7],
       [9]])

Having the vectors be rows or columns will _not_ affect the operation, so long as both vectors are the same shape.

In [22]:
# compute v + w (row vectors)

v.T + w.T 

array([[5, 7, 9]])

### What if our vectors have different shapes?

First, lets look at adding vectors with the same shape (row) but different sizes.

In [18]:
# A:



array([ 7,  9, 11])

We can see that the single value in vector '`w`' is added to all of the values on vetor '`v`'.

### $$\vec{v} + \vec{w} =
\left[ \begin{array}{c}
2&3&9
\end{array} \right] + \left[ \begin{array}{c}
2 
\end{array} \right] = 
\left[ \begin{array}{c}
2+2&3+2&9+2
\end{array} \right] = 
\left[ \begin{array}{c}
4&5&11
\end{array} \right]
$$

Lets see how this applies to vectors of different shapes.

In [ ]:
# A:



While we start with a vector of shape [1,3] and another that is [3,1], we end up with a matrix with a shape of [3,3].  How is this possible?

Below we can see that the first value in vector `w` is added to all of the values in vector `v` to make the first row of the matrix.  This process is repeated with the second and thrid values of vector `w` to create the respecting second and third rows of the resulting matrix.

### $$\vec{v} + \vec{w} =
\left[ \begin{array}{c}
1&2&3
\end{array} \right] + \left[ \begin{array}{c}
3 \\
6 \\
9
\end{array} \right] = 
\left[ \begin{array}{c}
1+3&2+3&3+3 \\
1+6&2+6&3+6 \\
1+9&2+0&3+9
\end{array} \right] = 
\left[ \begin{array}{c}
4&5&6 \\
7&8&9 \\
10&11&12
\end{array} \right]
$$

<a id="scalar-multiplication"></a>
### Scalar multiplication
We scale a vector with **scalar multiplication**, multiplying a vector by a scalar (single quantity):

### $$ 2 \left[ \begin{array}{c}
1 \\
3 \\
7
\end{array} \right] = 
 \left[ \begin{array}{c}
2 \cdot 1 \\
2 \cdot 3 \\
2 \cdot 7
\end{array} \right] = 
 \left[ \begin{array}{c}
2 \\
6 \\
14
\end{array} \right]$$

_It is kind of similar to adding vectors of different sizes._

In [23]:
# multiply v by 2

v*2

array([[2],
       [4],
       [6]])

If $\vec{a} = \left[ \begin{array}{c}
2 \\
1 
\end{array} \right]$ and $b = 3$:

$b*\vec{a} = 3*\left[ \begin{array}{c}
2 \\
1 
\end{array} \right] = \left[ \begin{array}{c}
6 \\
3 
\end{array} \right]$

![](./assets/images/scalar_multiplication_3a.png)

The nature of the operation remains the same for vectors with row shapes as well.

In [6]:
# A:


<a id="vector-norm"></a>
### Vector norm
The **magnitude** of a vector $\vec{v} \in \mathbb{R}^{n}$ in is interpretable as its length in n-dimensional space, and is calculable via the Euclidean distance:

$\vec{v} = \left[ \begin{array}{c}
v_{1} \\
v_{2} \\
\vdots \\
v_{n}
\end{array} \right]$

then $\| \vec{v} \| = \sqrt{v_{1}^{2} + v_{2}^{2} + ... + v_{n}^{2}}$

E.g. if $\vec{v} = 
\left[ \begin{array}{c}
3 \\
4
\end{array} \right]$, then $\| \vec{v} \| = \sqrt{3^{2} + 4^{2}} = 5$

This is also called the vector **norm**. You will see this often in machine learning as _least squares_.

In [25]:
# A:

v = np.array([[3],[4]])

np.linalg.norm(v)

5.0

#### Independent practice  
Use vectors `u` & `v`, given below, to calculate the following.  First calculate by hand, then with numpy.  

- Find sum of vectors `u` and `v`
- Find the difference between `u` and `v`
- Find the scalar product of `u` and `3`
- Find magnitude of vector `u`

In [27]:
u = np.array([3.0,4.0]).reshape((2,1))

v = np.array([2.0,1.0]).reshape((2,1))

In [28]:
# A: 
v+u



array([[ 5.],
       [ 5.]])

In [29]:
v-u


array([[-1.],
       [-3.]])

In [32]:
u*3


array([[  9.],
       [ 12.]])

In [33]:
np.linalg.norm(u)

5.0

<a id="dot-product"></a>
### Dot product
The **dot product** of two _n_-dimensional vectors is:

### $$ \vec{v} \cdot \vec{w} =\sum _{i=1}^{n}v_{i}w_{i}=v_{1}w_{1}+v_{2}w_{2}+\cdots +v_{n}w_{n} $$

So, if:

### $$\vec{v} = \left[ \begin{array}{c}
1 \\
3 \\
7
\end{array} \right], \vec{w} = \left[ \begin{array}{c}
1 \\
0 \\
1
\end{array} \right]$$

### $$ \vec{v} \cdot \vec{w} = 1*1 + 3*0 + 7*1 = 8 $$

In [4]:
# calculate the dot product

v = np.array([1,3,7]).reshape(1,3)
w = np.array([1,0,1]).reshape(3,1)
d = v.dot(w)

d

array([[8]])

<a id="matrix-multiplication"></a>
### Matrix multiplication
**Matrix multiplication**, $A_{mn} * B_{ij}$, is valid when the left matrix has the same number of columns as the right matrix has rows ($n = i$). Each entry is the dot product of corresponding row and column vectors.

![](./assets/images/matrix-multiply-a.gif)
(Image: mathisfun.com!)

### $$\left[ \begin{array}{c}
1 & 2 & 3  \\
4 & 5 & 6
\end{array} \right]*
\left[ \begin{array}{c}
7 & 8 \\
9 & 10 \\
11 & 12 
\end{array} \right] = 
\left[ \begin{array}{c}
1*7 + 2*9 + 3*11 & ... \\
... & ... \\
\end{array} \right]
= 
\left[ \begin{array}{c}
58 & 64 \\
139 & 154 \\
\end{array} \right]
$$

In [ ]:
# A:

<a id="the-identity-matrix"></a>
### The identity matrix
The **identity matrix**, $I_{n}$ is the matrix where $I_{n} A = A$. This is like multiplying by 1:

### $$ I \cdot \left[ \begin{array}{c}
a_{11} & a_{12} \\
a_{21} & a_{22} 
\end{array} \right] = \left[ \begin{array}{c}
a_{11} & a_{12} \\
a_{21} & a_{22} 
\end{array} \right]$$

E.g.:

### $$ \left[ \begin{array}{c}
1 & 0 \\
0 & 1 
\end{array} \right] \cdot \left[ \begin{array}{c}
3 & 4 \\
5 & 6 
\end{array} \right] = \left[ \begin{array}{c}
(1 \cdot 3 + 0 \cdot 5) & (1 \cdot 4 + 0 \cdot 6) \\
(0 \cdot 3 + 1 \cdot 5) & (0 \cdot 4 + 1 \cdot 6) 
\end{array} \right] =
\left[ \begin{array}{c}
3 & 4 \\
5 & 6 
\end{array} \right]$$

This is the matrix equivalent of multiplying a value times the identity 1.

### Independent Practice
Calculate the dor product of the below matrices by hand and then check your results using numpy.

### $$ \left[ \begin{array}{c}
1&2&3 \\
4&5&6
\end{array} \right] \cdot \left[ \begin{array}{c}
1&2 \\
3&4 \\
5&6
\end{array} \right]$$

In [5]:
# Create 2 x 3 matrix A, of type array
A = np.array([[1, 2, 3], [4, 5, 6]]) 
# Create 3 x 2 matrix B, of type array
B = np.array([[1, 2], [3, 4], [5,6]]) 

In [8]:
# A:

a = [(1*1 + 2*3 + 3*5  ), (2*1 + 4*2 + 3*6)]
b = [(1*4 + 3*5 + 5*6 ) ,(2*4 + 4)]

print a
print b

print a
print b

" "
c = a.dot(b)
c


[22, 28]
[49, 12]
[22, 28]
[49, 12]


AttributeError: 'list' object has no attribute 'dot'

<a id="applications-to-machine-learning"></a>
## Applications to machine learning
---

<a id="distance-between-actual-values-and-predicted-values"></a>

### Distance between actual values and predicted values
We often need to know the difference between predicted values and actual values.
We calculate this as:

### $$\| \vec{actual} - \vec{predicted} \| =\sqrt{(actual_1 - predicted_1)^2 + (actual_2 - predict_2)^2}$$

<a id="least-squares"></a>

### Least squares
Many machine learning models are composed in the following form:

### $$\min \| \vec{y} - f(X) \|$$

The goal is to minimize the distance between model predictions and actual data.

<a id="independent-practice"></a>
## Independent practice
---

Review the numpy operations, and try out their examples, here: http://docs.scipy.org/doc/numpy/reference/routines.linalg.html

<a id="additional-resources"></a>
## Additional resources
---

+ For a surprisingly comprehensive (yet dense!) review, be sure to check out [Linear algebra in four pages](http://www-bcf.usc.edu/~lototsky/MATH408/LinAlg1.pdf)
+ This [deck](http://cseweb.ucsd.edu/classes/wi05/cse252a/linear_algebra_review.pdf) provides great insight into linear operations and advanced geometric topics
+ Stanford's Review and Reference [26-page](http://cs229.stanford.edu/section/cs229-linalg.pdf) guide provides a nice review
+ Spend some time on [Khan Academy](https://www.khanacademy.org/math/linear-algebra/matrix-transformations#concept-intro)!