<img src="https://ga-dash.s3.amazonaws.com/production/assets/logo-9f88ae6c9c3871690e33280fcf557f33.png" style="float: left; margin: 10px;"> 
# Introduction to Numpy

---
Week 2

### LEARNING OBJECTIVES
*After this lesson, you will be able to:*
- Understand and demonstrate how to create and minipulate nummpy arrays (1D, 2D, 3D, ND)
- Understand and demonstrate how to use numpy methods (shape, mean, flatten)
- Understand and demonstrate how to slice arrays
- Understand and demonstrate how to broadcast arrays 


### STUDENT PRE-WORK
*Before this lesson, you should already be able to:*
- Understand and write basic python syntax
- Understand and minipulate list data objects



## Introduction 

![](http://static.wixstatic.com/media/7b913d_7d27b1ff5fe54cc79c80d2cc0e319d92~mv2.jpg/v1/fill/w_400,h_225/7b913d_7d27b1ff5fe54cc79c80d2cc0e319d92~mv2.jpg)


So for in the programm, you have been exposed to the building blocks of coding in python (data types, functions, objects) that enable you to communicate with the computer programmatically. Numpy is another building block, but Numpy brings us into the world of scientific computing. 

With Numpy, you'll be able create a version of list called arrays that have more features than list and allow us to minipulate and analysis data in a way that the python standard library does not. 

Numpy is a popular tool used by data scientist in order to clean, minipulate, and analyze data to that can understand what the data is telling us. 

![](http://mentat.za.net/numpy/numpy_advanced_slides/graphics/array_3x5x8.png)

## Array Operations 

Let's creat some arrays and explore some basic opperations.

In [3]:
import numpy as np
from scipy.ndimage import imread
from IPython.display import Image

In [4]:
# create an array called a with floats 
a = np.array([1.,3.,5.,6.])

In [10]:
b = [2.,4.,5.,6.]

In [6]:
# use the build-in function type to check the data type of a data object
type(a)

numpy.ndarray

In [7]:
# create an array by passing a list into it
np.ndarray

numpy.ndarray

In [11]:
type(b)

list

Numpy doesn't offically recognize rows and columns until we start building 2 dimensional array, also known as matricies. 1D array shapes simple display the number of elements. 

In [9]:
b.shape

AttributeError: 'list' object has no attribute 'shape'

In [33]:
[2,3] + [5,6]

[2, 3, 5, 6]

In [31]:
a

array([ 1.,  3.,  5.,  6.])

In [32]:
b 

array([ 2.,  4.,  5.,  6.])

In [13]:
# add arrays element-wise 
a+b

array([  3.,   7.,  10.,  12.])

In [14]:
# subtract arrays element-wise
a-b

array([-1., -1.,  0.,  0.])

In [15]:
# subtract arrays element-wise


array([ 0.5 ,  0.75,  1.  ,  1.  ])

In [16]:
# divided arrays element-wise
a/b

array([ 0.5 ,  0.75,  1.  ,  1.  ])

In [17]:
# multiply arrays element-wise 
a*b

array([  2.,  12.,  25.,  36.])

## You Try

Create a function that accepts two arrays and returns their sum in an array. Both arrays must be the same size. 

In [20]:
# your code goes here

def add_array(arry1, arry2):
    a = np.array(arry1)
    b = np.array(arry2)
    if len(a) == len(b):
        return a + b
    
add_array([2, 3, 5, 6], [2, 3, 5, 6])

array([ 4,  6, 10, 12])

## Indexing and Slicing Arrays

Slices are references to memory in the original array. Meaning that the result value(s) are not copies. 

In [22]:
# slicng 1D array elements 
new_arr = np.array([10,20,30,40,50])

In [23]:
# slicing to get all elements in return 
new_arr[:]

array([10, 20, 30, 40, 50])

In [24]:
# another way of slicing to get all elements in return 
new_arr[0:]

array([10, 20, 30, 40, 50])

In [10]:
# another way of slicing to get all elements in return 
new_arr[0:5]

In [11]:
# slice subset of elements
new_arr[0:2]

In [26]:
# get the last two values in the array
new_arr[-2:]

array([40, 50])

In [28]:
# get all but the last two values in the array (i.e. the first three values)
new_arr[0:3]
new_arr[:-2]

array([10, 20, 30])

Changing values in a slice also changes the original array. This happens becuase slices are references to the array. 

In [29]:
# setting 1D array elements 
new_arr = np.array([10,20,30,40,50])

In [30]:
# set a single element with a single value
new_arr[0] = 500
new_arr

array([500,  20,  30,  40,  50])

In [32]:
# set multiple elements with a single value
new_arr[:2] = [100,299]
new_arr[:]

array([100, 299,  30,  40,  50])

In [34]:
# set a multiple elements with different values
new_arr[0:2] = [80,90]
new_arr

array([80, 90, 30, 40, 50])

## You Try

Create a function accepts two arrays. Both arrays have 4 elements. The function must return the sum of the first two elements in one array with the last two elements of the second array. 

In [49]:
# your code goes here

def add_2(arg1, arg2):
    a = np.sum(arg1[0:2])
    b = np.sum(arg2[-2:])
    return a, b


add_2([100, 299,  30,  40,  50], [1, 2,  30,  40,  50])   
    

(399, 90)

## 2 Dimensional Arrays

In numpy, matricies are refered to as 2D arrays because they have two spatial dimensions--the up/down dimension and the left/right dimension. All of the 1D operations carray over to 2D arrays.

In [52]:
# 2D arrays
twod = [[1,2,3,4],[5,6,7,8]]

In [53]:
# array[row_index, column_index]
arry_2d = np.array(twod)
arry_2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [55]:
# index to reference entire first row
B2d = [[4,5,6,7],[6,7,8,9]]
B2d + twod

In [64]:
# index to reference entire second row
B2d = [[4,5,6,7],[6,7,8,9]]

arry_2d = np.array(B2d)

In [66]:
# index to reference first column value in first row
arry_2d[0, :2]

array([1, 2])

In [71]:
# index to reference last two column values in second row
arry_2d[1][-2:]

array([7, 8])

In [24]:
# set value in 2D array


In [25]:
# set single value in row one


In [26]:
# set multipal values in row two


In [73]:
A = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12],
              [13,14,15,16]])
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [86]:
A.shape
# ARRAY[row][col]
# ARRAY[row, col]

A[:2] 

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [27]:
# refernce the first three rows 


## You Try

Create a function that accepts two 2D arrays with dimensions (4,4). The function must return the first two rows of one array and the last two elements of the last row in the second array. 

In [ ]:
# your code goes here
def first_last(ar1, ar2):
        a = ar1.np.array([:2]) 
        b = ar2.np.array([1,-2:])
        return a , b

first_last(ar1, ar2)

### 2D Array Operations

In [87]:
a = np.array([[1,2,3], 
              [4,5,6]])

b = np.array([[2,2,2], 
              [4,4,4]])

In [89]:
# element-wise addition
a[0,2] + b[0,2]

5

In [90]:
# element-wise subtraction
a[0,2] - b[0,2]

1

In [91]:
# element-wise multiplication
a[0,2] * b[0,2]

6

### You Try

Create a function that accepts two 2D arrays and returns their difference. 

In [95]:
a = np.array([[1,2,3], 
              [4,5,6]])

b = np.array([[2,2,2], 
              [4,4,4]])

def diff(ar1, ar2):
    return ar1 - ar2

diff(a, b)
    

array([[-1,  0,  1],
       [ 0,  1,  2]])

### Masks

Mask are usually conditional statments used to filter out values in an array that we don't need or isolate values that we do need. 


In [96]:
A = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12],
              [13,14,15,16]])
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [103]:
# let's create a mask to remove all odd numbers
mask= A % 2 ==0

mask 

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]], dtype=bool)

In [107]:
A[mask].reshape(4,2)

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16]])

Masks can also be other arrays used to rearrange the rows 

In [77]:
# this mask will move the 2nd row to the first row, 
# the 3rd row to the 2nd row, 
# and the 1st row to the 3rd and 4th row
mask2 = np.array([2,3,1,1])
mask2

array([2, 3, 1, 1])

In [109]:
# mask can also be other arrays used to rearrange the rows 
B = A[mask].reshape(4,2)
B

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16]])

### You Try

Create a function masks all values that are greater than 10 for the following 2D array. 

In [132]:
Z = np.array([[1,4,6,9,11],
              [13,4,15,9,3]])

mask = Z > 0
Z[mask]

array([ 1,  4,  6,  9, 11, 13,  4, 15,  9,  3])

In [133]:
# your code goes here

def mask_10(arg):
    mask =  arg > 10
    return arg[mask]

mask_10(Z)

array([11, 13, 15])

## Multi-Dimensional Arrays

![](https://www.scirra.com/images/articles/3d_array.png)

Multi-dimensional arrays can be thought of as having multipal tables (2D matrices) stacked in a row. Multi-dimensional arrays can vary from 3 dimensions to N dimensions, where N is an finite, non-negative number. Because multi-dimensional arrays with more than 3 dimensions are very difficult to visualize, we will focus on dimenions of no greater than 3. 

Three-dimensional arrays are routinely encountered in computer vision. Color images have 3 dimensions: Red, Blue, and Green. Because all colors are a combination of these three colors, it is natural for an image to be represented by a 3 dimensional array. 


In [135]:
from IPython.display import Image
file_path = "/Users/Alexander/Downloads/GA_Onboarding/MacroHoneybee.jpg"
display_image = Image(file_path)
display_image

In [93]:
# load image and check shape
image = imread(file_path)
image.shape

(400, 600, 3)

In [94]:
# reduce number of values in each cell from 3 (RBG) to 2 (RB?)
red_image = image[:,:,0:2]
red_image.shape

(400, 600, 2)

In [95]:
# save reduced image to file
file_path_2 = "/Users/Alexander/Downloads/GA_Onboarding/MacroHoneybee_reduce.csv"
red_image.tofile(file_path_2)

In [97]:
from PIL import Image
# displace reduced image
img = Image.fromarray(red_image)
img.show()

Let's get a better understanding of how 3 dimensional arrays work by going through an example. 

The following 3D array shows that there are 2 rows and 3 columns. Within each cell of the 2 by 3 table/matrix/plane (whatever helps you understand) there are 4 values. 

![](http://1.bp.blogspot.com/_kLg3mPfGL6E/S_xsBdb5xOI/AAAAAAAAALQ/eGJlCrpaDEY/s400/three-dimensionsl+array.jpg)

In [136]:
# let's create the 3D array in the image
B = np.array([ [  [1,2,3,4],    [5,6,7,8],     [9,10,11,12] ],
              [ [13,14,15,16], [17,18,19,20], [21,22,23,24] ] ])

In [137]:
# the print out shows all the values in each row, which doesn't illuminate the 3D aspect of this array
B

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [138]:
# array[row_index, column_index, depth_index]
B[:]

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [143]:
# reference 1st row
B[0]

array([1, 2, 3, 4])

In [155]:
# reference 1st row and first two columns
B[0][:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [158]:
# reference 2nd row and last two columns and first two values 
B[1,-2:,:2]

array([[17, 18],
       [21, 22]])

### You Try

Create a 3D array with the following dimensions: (3,2,2)

In [164]:
# your code goes here
# array[row_index, column_index, depth_index]

x = np.array([[
        [ 5,  6],
        [ 9, 10]],

       
        [[17, 18],
        [21, 22]],
             
        
        [[17, 18],
        [21, 22]]])

x.shape


(3, 2, 2)

## Array Methods

**where( )** method takes a conditional statement and returns elements in the pass array that satisfy the condition. 

In [ ]:
a = np.array([1,2,3,4,5])

In [165]:
# where method
np.where(a > 3)

(array([1, 1, 1]), array([0, 1, 2]))

In [166]:
# Flattening arrays vs unravel 
b = np.array([[1,2,3,4,5], 
              [6,7,8,9,10]])
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

**flatten( )** converts a multidimensional
array into a 1-D array. The new
array is a copy of the original data.

In [167]:
# a.flatten() converts a multidimensional array into a 1-D array. 
# The new array is a copy of the original data.
b.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Changing b does not change c since c is a copy of b

In [168]:
c[0] = 100
c

NameError: name 'c' is not defined

In [ ]:
b

**ravel( )** is the same as **flatten( )**, but it returns a reference (or view) of the array
if possible. Otherwise the new array copies the data.

In [169]:
# ravel flattens the array
b.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Changing b does change d

In [170]:
d = b.ravel()

In [171]:
d[0] = 100
d

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [ ]:
# because d and b reference the same memory space, b's first element also changes value
b

### Check for Understanding
--------

Think of a reason when using ravel over flatten is a good idea, and vice versa. 

--------


## Transpose

**Transpose** is a mathematical operation in linear algebra that rotates a matrix around its diagonal. 



In [39]:
# Transpose
A = np.array([[0,1],[2,3]])

In [41]:
# Transpose returns a reference of the array
B = A.T
B[0,0] = 100

In [40]:
# A is also has its value at (0,0) changed

## Reshaping arrays

**Reshaping arrays** allows you to transform the shape of a matrix so long as the dimenions you pick doesn't change the number of elements needed to fill the arrary. 

In [ ]:
# reshaping arrays
C = np.array([[1,2,3], 
              [4,5,6]])
C

In [42]:
# two rows, three columns


The reshape of an array is not saved to memory unless you save the result to a variable. 

In [ ]:
C = C.reshape((6,1))
C

## Diagonals

**Diagonals** allows you to get the diagonal values of your matrix (2D array). The diagonal values of a matrix have a very speical place in linear algebra. Which you'll be exposed to in week 2. For now, just know that numpy has methods for retriving and minipulating them. 

In [175]:
D = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [176]:
# Diagonals

D.diagonal()

array([1, 5, 9])

## Array Data Types

Numpy has methods that allow you to check what is the data type of your elements as well as changing the data type of your elements. 

In [ ]:
# specifying DTypes
D.dtype

In [ ]:
E = np.array(['a', 'b', 'c'])
E.dtype

In [ ]:
a = np.array([1,2,3,4,5])
a

In [ ]:
a.dtype

In [44]:
# chang data type from int to float and save to memory 


In [ ]:
a.dtype

### You Try

Perform the follow operations:

1. Take the transpose of Z
2. Add Z to the transpose of Z
3. Take the diagonal of the result form step 2. 
4. Change the data type to strings

In [ ]:
z = np.array([[1,2,3], 
              [4,5,6], 
              [7,8,9]])

In [ ]:
# your code goes here

## Statistics in Numpy ( average,min, max , st, median, var)

Numpy has several useful methods for getting a statistical description of your data. Because the course has not formally covered statistics yet, I'll only cover the average method. 

In [177]:
# Array calculation methods: min, max, average, st, median, var
b = np.array([[2., 4.],
              [1., 3.]])

In [183]:
# average of columns
np.mean(b, axis = 0)

array([ 1.5,  3.5])

In [184]:
# average of rows
np.mean(b, axis = 1)

array([ 3.,  2.])

In [182]:
# average of entire array
np.mean(b)

2.5

## Concatenation 

**concatenate** The input arrays $(a_{0},a_{1},…,a_{N})$ are concatenated along the given axis. 

In [185]:
# Concatonate arrays
A = np.array([[1,2], 
              [3,4]])

B = np.array([[5,6], 
              [7,8]])

In [189]:
# concatonate along columns
np.concatenate((A,B), axis =0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [190]:
# concatonate along rows
np.concatenate((A,B), axis =1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

Other methods that accomplish the same thing

In [192]:
# vertical stacking (by rows)
z = np.array([1, 2, 5, 6])
m = np.array([3, 4, 7, 8])      

np.vstack((z,m))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [193]:
# horizontal stacking (by columns)
np.hstack((z,m))

array([1, 2, 5, 6, 3, 4, 7, 8])

### You Try

1. Concatenate the follow two arrays so that their rows are stacked on top of each other.
2. Find the average of the resulting rows. 
3. Find the average of the resulting columns. 

In [197]:
Y = np.array([[1,2],[3,4],[5,6]])
X = np.array([[2,2],[2,2], [2,2]])

In [208]:
# your code goes here
cat = np.vstack((Y,X))
row =np.mean(cat,axis = 1 )
col =np.mean(cat,axis = 0 )
together = np.hstack((row,col))


print together

[ 1.5  3.5  5.5  2.   2.   2.   2.5  3. ]


## BroadCasting

![](http://www.scipy-lectures.org/_images/numpy_broadcasting.png)

In [209]:
# array broadcasting
a = np.array([[1],
              [2],
              [4]])

b = np.array([2, 4, 6])

In [210]:
# add a and b 
a+b


array([[ 3,  5,  7],
       [ 4,  6,  8],
       [ 6,  8, 10]])

In [211]:
# subtract a and b
a-b

array([[-1, -3, -5],
       [ 0, -2, -4],
       [ 2,  0, -2]])

In [212]:
# take the product of a and b
a*b

array([[ 2,  4,  6],
       [ 4,  8, 12],
       [ 8, 16, 24]])